name: First Workflow

on: push

jobs: 
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "Hi, This is my first my github action"
      - name: Checking linting
        run: echo "Checking linting"
